### ISSUE TITLE
能有一个从零部署的说明吗？

### ISSUE THREAD

**Issue by KuMuRen** [wxywb/history_rag#11]
可以增加一个windows从零开始部署的说明吗？我用了一天总算勉强把milvus搞出来了。现在按命令看是有milvus-etcd、milvus-minio、milvus-standalone，也安装了最新的python，但是其他的步骤应该怎么操作？
![Clip_2024-01-29_13-31-50](https://github.com/wxywb/history_rag/assets/158017017/37e283d6-c850-41eb-9249-99ac925be4a8)

**Comment by wxywb** [comment]
看起来windows和linux/mac不一样的点应该是这个环境变量， 当然你得有python(推荐使用anaconda)
在环境变量里设置openai_key ，按下图step3(所有的环境变量都差不多，比如通义千问)
<img width="867" alt="截屏2024-01-29 下午2 12 24" src="https://github.com/wxywb/history_rag/assets/5432721/e37843e2-965d-4bb6-8b45-738d2e53dd09">

**Comment by KuMuRen** [comment]
设置好变量了，现在通过openai的演示也返回了一个音频，但是提示少个dashscope的模型？？
![Clip_2024-01-29_19-42-38](https://github.com/wxywb/history_rag/assets/158017017/29a42ccc-4e78-4c7d-b1c6-5bc50154948d)
这个怎么处理啊，我用的是本地milvus

**Comment by KuMuRen** [comment]
![2](https://github.com/wxywb/history_rag/assets/158017017/56c3b6db-dc89-488a-8c58-96f67263062b)
这是现在的milvus运行情况

**Comment by wxywb** [comment]
pip install dashscope装一下这个吧，我把依赖给加上

**Comment by wxywb** [comment]
> pip install dashscope装一下这个吧，我把依赖给加上

看了一下，有dashscope的，执行`pip install -r requirements.txt`

**Comment by KuMuRen** [comment]
谢谢

**Comment by KuMuRen** [comment]
pip install dashscope
pip install pymilvus
pip install yaml(pip install pyyaml)
pip install EasyDict

pip install transformers
pip install torch sentence-transformers。
一共拉了六个，然后yaml下不来，就查了一下，别人说pyyaml也可以，就拉的pyyaml。现在跑起来了，正在建立索引。
希望能更新下readme，要不然跟我一样不是计算机专业的第一次跑实在是太难受了。
第一个点是添加那个变量。
然后docker我windows不会下milvus，是弄下来了milvus-standalone-docker-compose.yml，然后cmd命令（docker-compose -f milvus-standalone-docker-compose.yml up -d）安装的。
接着就是那些包了。

**Comment by wxywb** [comment]
以后可以先试着问一下chatgpt，把报错信息啥的都发给它，这样能少踩不少坑。
