### ISSUE TITLE
Unknow Model 的问题

### ISSUE THREAD

**Issue by Centiselal** [wxywb/history_rag#13]
在运行 
python cli.py
(rag) milvus
后就会出现这样的问题
![wrong_1](https://github.com/wxywb/history_rag/assets/135585383/a5fc23c7-2071-43b5-963f-422ca3b92433)
![wrong_2](https://github.com/wxywb/history_rag/assets/135585383/1d999de9-7f94-4113-8e3b-113df7dc679a)
图1是报错的信息，图2是获取的OPEN_AI_KEY
我在想是不是OPEN_AI_KEY的问题
请大佬解答

**Comment by Centiselal** [comment]
选的是Zilliz Cloud Pipelines方案

**Comment by wxywb** [comment]
pip install -U openai把openai试试呢，gpt-4-0125 preview比较便宜也比较新

**Comment by wxywb** [comment]
这俩选一个，(gpt-4-1106-preview, gpt-4),前面这个便宜一半

**Comment by taihaozesong** [comment]
> 我运行pip install -U openai 后还是出现的这个问题 我也尝试 pip uninstall openai pip install openai 后，仍无效 这次我在虚拟的环境下安装运行 仍旧是gpt-4-0125 为什么就只是这个模型呢o(╥﹏╥)o，请大佬指教

这个其实不是openai的版本问题，他是在llama_index里掉的，那个里面dict写死了， 可以在python对应版本的site-packages/llama_index/llms/openai_utils.py 里L31 `GPT4_MODELS: Dict[str, int] = {` 加入，其实我好奇作者为啥要用老版本的llama_index, 这个问题在三天前被修复了, 在 https://github.com/run-llama/llama_index/blob/main/llama_index/llms/openai_utils.py#L39

**Comment by wxywb** [comment]
其实当初是想让大家强行升级llama-index了，知识过了不久这个版本就落后了。

**Comment by wxywb** [comment]
> > 我运行pip install -U openai 后还是出现的这个问题 我也尝试 pip uninstall openai pip install openai 后，仍无效 这次我在虚拟的环境下安装运行 仍旧是gpt-4-0125 为什么就只是这个模型呢o(╥﹏╥)o，请大佬指教
> 
> 这个其实不是openai的版本问题，他是在llama_index里掉的，那个里面dict写死了， 可以在python对应版本的site-packages/llama_index/llms/openai_utils.py 里L31 `GPT4_MODELS: Dict[str, int] = {` 加入，其实我好奇作者为啥要用老版本的llama_index, 这个问题在三天前被修复了, 在 https://github.com/run-llama/llama_index/blob/main/llama_index/llms/openai_utils.py#L39
> 
> 最简单的方法应该是更新llama_index
> 
> ```shell
> pip install llama-index==0.9.39
> ```

因为当初想让大家强行升级llama-index的版本，只是这个版本在今天就落后了。

**Comment by Centiselal** [comment]
好的，感谢感谢
