### ISSUE TITLE
[Feature Requests] 关于WebUI与返回检索内容的需求

### ISSUE THREAD

**Issue by taihaozesong** [wxywb/history_rag#14]
1. 后期有打算提供web ui嘛？目前在wsl环境会出现ANSI 转义序列的问题，可以通过`import readline`解决，但是还是不够好看
2. 能否只返回topk的chunk(检索得到的原文内容)，不进行llm具体调用？
3. 可以在FAQ里列一下一般一个问题的价格？我个人实测GPT4 turbo的价格在每个问题0.05$左右

**Comment by wxywb** [comment]
- 这个项目没有webui，但学一会儿gradio你应该就可以做一个界面了，或者你可以用[rich](https://github.com/Textualize/rich)做一些美化。
- 将[输出](https://github.com/wxywb/history_rag/blob/master/executor.py?plain=1#L209) 替换为 `response = ''`, debug开关打开。`contexts`就是你要的。
- 可以，当时只是测试这些参数可以满足我的质量需求，你可以通过减小rerank_topk，,window_size, 以及更换国产llms(通义千问，chatglm, 百川...)来降低成本，我没有这些账号。

**Comment by taihaozesong** [comment]
解决了，感谢！
