### ISSUE TITLE
可以使用GPT3.5的API吗？

### ISSUE THREAD

**Issue by wei851246721** [wxywb/history_rag#15]

**Comment by wxywb** [comment]
我在几个问题上产生了不太能接受的幻觉，就用gpt-4了，你可以自己试试几个例子对比一下。

**Comment by taihaozesong** [comment]
俺试的时候幻觉太严重了, 模型是gpt-3.5-turbo-1106
> (rag)问题:关公有哪些重要战绩，对手是谁?
关公有几个重要的战绩，对手分别是颜良、文丑、张辽、关羽、孙权等。《三国志·三国志卷六十四 蜀书十九 诸葛滕二孙
濮阳传第十九》中提到了关羽远远望见颜良的帅旗车盖，策马上前刺杀颜良于万马军中，将其首级割下返回，袁绍军中的
将领们没人敢出阵阻挡，于是解除白马之围。曹操当即上奏朝廷封关羽为汉寿亭侯。另外，《三国志·三国志卷五十五 蜀
书十 程黄韩蒋周陈董甘凌徐潘丁传第十》中也提到了关羽生擒了颜良、文丑，被升为昭武将军，封爵西安乡侯。此外，关
羽还鲁与张辽、孙权等作战。

**Comment by wei851246721** [comment]
> 我在几个问题上产生了不太能接受的幻觉，就用gpt-4了，你可以自己试试几个例子对比一下。

如果要用GPT3.5 API的话，需要修改程序里面的什么部分呢

**Comment by taihaozesong** [comment]
> 如果要用GPT3.5 API的话，需要修改程序里面的什么部分呢

可以改这一行 https://github.com/wxywb/history_rag/blob/master/cfgs/config.yaml#L2

**Comment by KuMuRen** [comment]
3.5只能说是，能用，不过对现在来说，我们没有gpt4的api，勉强检索一下也够了。
(rag) 问题: 谁被称为梦中宰相
不知道
(rag) 问题: 武丁做梦后找到了谁
武丁做梦后找到了一个圣人，名叫说。他派百官各处寻找，终于在一个叫傅险的地方找到说。这时， 说正服刑，在傅险筑路，把他带来见武丁，武丁说“：正是他。[《史记·殷本纪》]

**Comment by wei851246721** [comment]
> > 如果要用GPT3.5 API的话，需要修改程序里面的什么部分呢
> 
> 可以改这一行 https://github.com/wxywb/history_rag/blob/master/cfgs/config.yaml#L2

感谢感谢 我晚上回家试一下 想问下你试过不检索历史，而是一些文档或者论文之类的吗

**Comment by KuMuRen** [comment]
> > > 如果要用GPT3.5 API的话，需要修改程序里面的什么部分呢
> > 
> > 
> > 可以改这一行 https://github.com/wxywb/history_rag/blob/master/cfgs/config.yaml#L2
> 
> 感谢感谢 我晚上回家试一下 想问下你试过不检索历史，而是一些文档或者论文之类的吗

他这个用的是txt文档，你放什么，建立什么文件的引擎是你自己的事。你可以参考一下那些txt文件来自己改动自己的文件去弄。另外每次检索最好是重复提问5、6次，然后选取最好的的结果。

**Comment by wei851246721** [comment]
> > > > 如果要用GPT3.5 API的话，需要修改程序里面的什么部分呢
> > > 
> > > 
> > > 可以改这一行 https://github.com/wxywb/history_rag/blob/master/cfgs/config.yaml#L2
> > 
> > 
> > 感谢感谢 我晚上回家试一下 想问下你试过不检索历史，而是一些文档或者论文之类的吗
> 
> 他这个用的是txt文档，你放什么，建立什么文件的引擎是你自己的事。你可以参考一下那些txt文件来自己改动自己的文件去弄。另外每次检索最好是重复提问5、6次，然后选取最好的的结果。

好的，他文档里面确实都是txt，那我可以用PDF吗，或者说txt与PDF对于引擎来说有什么不同吗

**Comment by wxywb** [comment]
1.  如果你使用pdf的话，先使用zilliz pipeline方案试一下好了
2. 对其他文本可能存在的问题，是你需要把`HistorySentenceWindowNodeParser`换成llamaindex中`SentenceWindowNodeParse`,因为`HistorySentenceWindowNodeParser`假定文本都是这种格式
```markdown
xx传
  xxxxxxxxxxxxxx
```

**Comment by FoilHao** [comment]
> > 如果要用GPT3.5 API的话，需要修改程序里面的什么部分呢
> 
> 可以改这一行 https://github.com/wxywb/history_rag/blob/master/cfgs/config.yaml#L2
配置修改为gpt-3.5-turbo后仍然会报错，超quota，请问用gpt3.5是还需要修改其他地方吗
openai.RateLimitError: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

**Comment by wei851246721** [comment]
> > > 如果要用GPT3.5 API的话，需要修改程序里面的什么部分呢
> > 
> > 
> > 可以改这一行 https://github.com/wxywb/history_rag/blob/master/cfgs/config.yaml#L2
> > 配置修改为gpt-3.5-turbo后仍然会报错，超quota，请问用gpt3.5是还需要修改其他地方吗
> > openai.RateLimitError: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

换为gpt-3.5-turbo-1106试一下

**Comment by wxywb** [comment]
> > > 如果要用GPT3.5 API的话，需要修改程序里面的什么部分呢
> > 
> > 
> > 可以改这一行 https://github.com/wxywb/history_rag/blob/master/cfgs/config.yaml#L2
> > 配置修改为gpt-3.5-turbo后仍然会报错，超quota，请问用gpt3.5是还需要修改其他地方吗
> > openai.RateLimitError: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

You exceeded your current quota, 看起你已经超出你使用openai的额度了，得充值，或者升级

**Comment by wei851246721** [comment]
![image](https://github.com/wxywb/history_rag/assets/59242319/03f3f970-17c2-4698-8b0e-9f7b6e31d302)

我已经把executor.py里面的HistorySentenceWindowNodeParser全部换成 了SentenceWindowNodeParse，但运行时会报错
![image](https://github.com/wxywb/history_rag/assets/59242319/33404855-15e6-44ed-ab03-30a2a7052351)

**Comment by wxywb** [comment]
> ![image](https://private-user-images.githubusercontent.com/59242319/302029384-03f3f970-17c2-4698-8b0e-9f7b6e31d302.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY5NTc2MjUsIm5iZiI6MTcwNjk1NzMyNSwicGF0aCI6Ii81OTI0MjMxOS8zMDIwMjkzODQtMDNmM2Y5NzAtMTdjMi00Njk4LThiMGUtOWY3YjZlMzFkMzAyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAzVDEwNDg0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVlZGY5NWZkY2E0MGNmZWU5ZDU0OWQxMDIxMzk5NmI2OTM0NTI2ZWY5ZTc5ODA3OGQwNDNhNDdjZTNhYWNhNzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yrgR8KxxtJcOZZPcHtMx06Mc76r9DvjdosEaJgm8K7E)
> 
> 我已经把executor.py里面的HistorySentenceWindowNodeParser全部换成 了SentenceWindowNodeParse，但运行时会报错 ![image](https://private-user-images.githubusercontent.com/59242319/302029373-33404855-15e6-44ed-ab03-30a2a7052351.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY5NTc2MjUsIm5iZiI6MTcwNjk1NzMyNSwicGF0aCI6Ii81OTI0MjMxOS8zMDIwMjkzNzMtMzM0MDQ4NTUtMTVlNi00NGVkLWFiMDMtMzBhMmE3MDUyMzUxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAzVDEwNDg0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNkNDdlMzIwOGRkZWUxNGQ1MDBkNDRhYzc0YmYxODMyNzYzMGQzYjViY2FlMWNhMWE5YWRkYjVhMzc1NzZjZGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tU_oYq_JRXnDZd8gnFSK_O4-kWhDUVDrHps4704ci4U)
换成
```python
from llama_index.node_parser import SentenceWindowNodeParser
``` 
以及这一个地方也要改
https://github.com/wxywb/history_rag/blob/90272e35f9c27a1a7d141183f6b48145c8f06982/executor.py#L102

**Comment by wei851246721** [comment]
我更改了这几个地方 
![image](https://github.com/wxywb/history_rag/assets/59242319/d12df9f0-7827-4679-a3dc-ae57a4c019d5)
![image](https://github.com/wxywb/history_rag/assets/59242319/d240e2f0-09ec-4470-8d93-a055b96361ea)
![image](https://github.com/wxywb/history_rag/assets/59242319/4308a4a6-eaf8-4a84-86f4-190538e9fa40)

但是build时会报 只有github上以txt结尾或文件夹可以被支持。

**Comment by wxywb** [comment]
你如果用的是pipeline的话不需要改的，那个是milvus方案

**Comment by wei851246721** [comment]
我用的pipeline方案，你的意思是完全不修改，直接build pdf文件吗？

**Comment by wei851246721** [comment]
> 但是build时会报 只有github上以txt结尾或文件夹可以被支持。

但是这样会报告： 只有github上以txt结尾或文件夹可以被支持。

**Comment by wei851246721** [comment]
> > 但是build时会报 只有github上以txt结尾或文件夹可以被支持。
> 
> 但是这样会报告： 只有github上以txt结尾或文件夹可以被支持。

比如想构建： build https://raw.githubusercontent.com/wei851246721/master/zilliz_paper_material/InfiniBand接口通信控制器的研究与FPGA实现.pdf

**Comment by wei851246721** [comment]
> > 但是build时会报 只有github上以txt结尾或文件夹可以被支持。
> 
> 但是这样会报告： 只有github上以txt结尾或文件夹可以被支持。

比如想构建：
https://raw.githubusercontent.com/wei851246721/zilliz_paper_material/master/InfiniBand接口通信控制器的研究与FPGA实现.pdf

**Comment by wxywb** [comment]
@wei851246721 
我现在明白的你的意思了
https://github.com/wxywb/history_rag/blob/90272e35f9c27a1a7d141183f6b48145c8f06982/executor.py#L296-L298
297行改成
```python
 elif path.endswith('.txt') or path.endswith('.pdf'):
```

**Comment by wxywb** [comment]
可以，开启 -d ，看一下召回的片段

**Comment by wei851246721** [comment]
召回的片段倒是很多，但最后给的答案是无效的
![image](https://github.com/wxywb/history_rag/assets/59242319/89c4bf7e-0ccb-426f-b8ed-5050e4154a5e)

**Comment by wxywb** [comment]
你这都算不上问题， 比如你可以试试 “ QP Verb 命令模块是什么？”

**Comment by wei851246721** [comment]
我试了下确实不能像我之前那样提问，需要提问中有比较精确的关键词，那么它回答正确概率很高
