### ISSUE TITLE
Empty Response

### ISSUE THREAD

**Issue by wei851246721** [wxywb/history_rag#18]
![image](https://github.com/wxywb/history_rag/assets/59242319/7801855e-61a9-4c8f-bb83-5532ae8b8851)

我提出了问题，但返回Empty Response，这是为什么呢？

**Comment by wxywb** [comment]
因为你还没有build index

**Comment by wei851246721** [comment]
> 因为你还没有build index

我 build data 了 但还是不行 换需要 build 什么呢

**Comment by wxywb** [comment]
提示没有找到，你要完整的复制那句话，`build data/history_24/baihuasanguozhi.txt` 这句
