### ISSUE TITLE
Milvus方案与Zilliz Cloud Pipelines方案 结果不同

### ISSUE THREAD

**Issue by wei851246721** [wxywb/history_rag#23]
![image](https://github.com/wxywb/history_rag/assets/59242319/bd44fed4-6622-407e-a53e-a117539aedba)
Milvus方案是成功回复的

![image](https://github.com/wxywb/history_rag/assets/59242319/3e6b459f-6fa4-42a3-8669-740a134179c1)
Zilliz Cloud Pipelines方案却提示API不行，是因为我用了中专站导致的吗？

llm:
    name: "gpt-3.5-turbo-1106"
    temperature: 0.01
    api_base : "https://one.aiskt.com/v1"

**Comment by wxywb** [comment]
你的第二个和第一个不是一个key吗？

**Comment by wei851246721** [comment]
> 你的第二个和第一个不是一个key吗？

是一个啊 都是一样的环境，只换了Pipelines方案

**Comment by wxywb** [comment]
> > 你的第二个和第一个不是一个key吗？
> 
> 是一个啊 都是一样的环境，只换了Pipelines方案

1.我看了一下pipeline的api_base处理代码和milvus是一样的
2.由于我没有中转站账户，所以没办法复现你的问题
3.你可以在242行前加上`print(api_base)`,看一下api_base是否正确传入
https://github.com/wxywb/history_rag/blob/d736f43760e8e512e64073a18c932261978cfa7e/executor.py#L240-L243

**Comment by wei851246721** [comment]
![image](https://github.com/wxywb/history_rag/assets/59242319/09a6ae70-afc4-43af-aca5-daa09ba14504)
api-base是正确的，但是还打印了一句
Embeddings have been explicitly disabled. Using MockEmbedding. 不知道是否正确

但是最后错误还是跟openai api相关的

**Comment by wxywb** [comment]
和这个没关系，我感觉我解决不了，你再检查一下你的环境变量里的api key

**Comment by wei851246721** [comment]
> 和这个没关系，我感觉我解决不了，你再检查一下你的环境变量里的api key

好吧，环境变量是没问题的，这个问题确实不清楚是什么导致的

**Comment by wxywb** [comment]
看起来这个问题得到了修复
https://github.com/wxywb/history_rag/pull/26
