### ISSUE TITLE
pipeline方案返回的相关文献没有出处的信息

### ISSUE THREAD

**Issue by decajoin** [wxywb/history_rag#28]
这是milvus的返回
![image](https://github.com/wxywb/history_rag/assets/134501931/d13c5001-b451-43a0-ab14-ee658d32f22a)
这是pipeline的返回
![image](https://github.com/wxywb/history_rag/assets/134501931/28e817cf-05ac-4d67-adf3-0f0d4a4f8284)
想请教一下这个问题有解决方法吗，谢谢 ^_^

**Comment by wxywb** [comment]
这个我之后处理一下

**Comment by decajoin** [comment]
好的，感谢您的回复 😁
