### ISSUE TITLE
pipeline方案使用qwen作为LLM时，无法正常使用

### ISSUE THREAD

**Issue by decajoin** [wxywb/history_rag#30]
用qwen作为LLM，用命令python cli.py --cfg cfgs/config_qwen.yaml启动，使用mlivus方案是正常的，但是使用pipeline方案的时候调用的模型却是LlamaIndex默认的gpt-3.5-turbo。请问这个问题怎么解决呢，期待您的回复，谢谢您。
![image](https://github.com/wxywb/history_rag/assets/134501931/e177ae2f-8025-4af1-9a53-749788dad655)

**Comment by wxywb** [comment]
我看有一个pr是解决api_base的问题，感觉和这个可能是一个问题，你是不是没更新，git pull一下呢

**Comment by decajoin** [comment]
更新了可以正常使用了，感谢你的解答 😄
