### ISSUE TITLE
覆写overwirite为true时，_initialize_pipeline报错，提示_initialize_pipeline()未传入参数

### ISSUE THREAD

**Issue by BetterAndBetterII** [wxywb/history_rag#36]
位置：executor.py 中 PipelineExecutor 中的def build_index(self, path, overwrite)方法，覆写时调用self._initialize_pipeline()

当executor创建索引时（build_index函数）覆写overwirite为true时，_initialize_pipeline报错，_initialize_pipeline()未传入参数

![image](https://github.com/wxywb/history_rag/assets/141388234/3c71e583-0416-4237-9829-658f0f106e2b)

**Comment by wxywb** [comment]
看起来应该是这个PR https://github.com/wxywb/history_rag/pull/26/files 漏掉了一些情况，我有空的时候会补上的。

**Comment by wxywb** [comment]
https://github.com/wxywb/history_rag/blob/c7249f5ff35aa8cead1b38753ac37cf6928d83ef/executor.py#L296
更新了一下这个地方

**Comment by BetterAndBetterII** [comment]
修复可用
