### ISSUE TITLE
使用zilliz构建数据库失败

### ISSUE THREAD

**Issue by PaperPlaneDeemo** [wxywb/history_rag#39]
![PixPin_2024-02-11_13-49-32](https://github.com/wxywb/history_rag/assets/26437093/11f3e684-a17c-410e-aad6-468c2ee80d33)
我想构建一个基于三体小说的问答机器人，使用命令build https://raw.githubusercontent.com/PaperPlaneDeemo/santi/main/santi.txt后半段为我自己上传到GitHub的三体小说全文
执行一段时间后报错
Traceback (most recent call last):
  File "D:\Program\history_rag\cli.py", line 120, in <module>
    cli.run()
  File "D:\Program\history_rag\cli.py", line 53, in run
    self.parse_input(command_text)
  File "D:\Program\history_rag\cli.py", line 65, in parse_input
    self.build_index(path=commands[1], overwrite=False)
  File "D:\Program\history_rag\cli.py", line 92, in build_index
    self._executor.build_index(path, overwrite)
  File "D:\Program\history_rag\executor.py", line 324, in build_index
    self.index.insert_doc_url(
  File "D:\Program\history_rag\custom\zilliz\base.py", line 132, in insert_doc_url
    raise RuntimeError(response.text)
RuntimeError: {
  "message":"The upstream server is timing out"
}
查看zilliz数据库中只构建了几百字的向量数据库，请问是网络连接的问题吗？还是上传文件或构建数据库有时间或空间限制？

**Comment by wxywb** [comment]
我也复现了这个问题，我会研究处理一下。

**Comment by PaperPlaneDeemo** [comment]
会考虑embedding方案使用openai的模型吗？

**Comment by PaperPlaneDeemo** [comment]
> 我也复现了这个问题，我会研究处理一下。

重新检查了数据库，虽然构建报错了，但小说所有内容已经全部保存，可以正常使用

**Comment by wxywb** [comment]
这个是由于zilliz cloudpipeline目前使用的是同步接口，不适合太长时间的embedding计算，所以支持的单个文件不能太大，会报超时错误，但依然会插入数据，除非数据触发chunk_size的限制。在异步模式上线后，这些限制就会大幅降低。zilliz cloud pipeline最近更新了openai的embedding，我会添加一下。

**Comment by PaperPlaneDeemo** [comment]
> 这个是由于zilliz cloudpipeline目前使用的是同步接口，不适合太长时间的embedding计算，所以支持的单个文件不能太大，会报超时错误，但依然会插入数据，除非数据触发chunk_size的限制。在异步模式上线后，这些限制就会大幅降低。zilliz cloud pipeline最近更新了openai的embedding，我会添加一下。

感谢回复，这个项目很有用，谢谢大佬！
