### ISSUE TITLE
ValueError

### ISSUE THREAD

**Issue by HITCJK** [wxywb/history_rag#42]
选择milvus方案后出现：ValueError: Unrecognized model identifier in BAAI/bge-base-zh-v1.5. Should contains one of 'bert', 'openai-gpt', 'gpt2', 'transfo-xl', 'xlnet', 'xlm', 'roberta, 'ctrl'并直接退出
<img width="1004" alt="PixPin_2024-02-16_23-50-56" src="https://github.com/wxywb/history_rag/assets/151022539/f24c4307-ed82-4386-9f08-07f8533cc12e">

**Comment by wxywb** [comment]
请看一下你的transformers版本
```bash
pip list |grep transformers
```

**Comment by HITCJK** [comment]
> 请看一下你的transformers版本
> 
> ```shell
> pip list |grep transformers
> ```

版本是2.1.1，请问该使用哪个版本？

**Comment by wxywb** [comment]
这个有点老了，用4.36.0吧

**Comment by HITCJK** [comment]
> 这个有点老了，用4.36.0吧

已解决，感谢
