### ISSUE TITLE
ImportError:cannot import name 'ServiceContext' from 'llama_index.core'

### ISSUE THREAD

**Issue by von-eureka** [wxywb/history_rag#51]
WSL2 Ubuntu环境下提示cannot import name 'ServiceContext' from 'llama_index.core'，llama-index版本是0.9.39

**Comment by von-eureka** [comment]
我尝试使用 `pip install llama_index.core`重新安装之后，报错变成了
> ValidationError
1 validation error for DataSource
 component_type
subclass of BaseComponent expected (type=type_error.subclass; expected_class=BaseComponent)
  File "/home/ureka/history_rag-master/executor.py", line 12, in <module>
    from llama_index.core import ServiceContext, StorageContext
pydantic.v1.error_wrappers.ValidationError: 1 validation error for DataSource
component_type
  subclass of BaseComponent expected (type=type_error.subclass; expected_class=BaseComponent)

**Comment by wxywb** [comment]
```bash
pip list|grep llama
```

**Comment by von-eureka** [comment]
>llama-index                              0.9.39
llama-index-core                         0.10.13
llamaindex-py-client                     0.1.13

**Comment by wxywb** [comment]
把这些都pip uninstall
然后只装这个llama-index 0.9.39

**Comment by von-eureka** [comment]
按照`pip list|grep llama`操作以后，返回的结果是`llama-index  0.9.39`，但是运行后报错：
>ImportError: cannot import name 'ServiceContext' from 'llama_index.core' (/home/ureka/.local/lib/python3.10/site-packages/llama_index/core/__init__.py)

**Comment by wxywb** [comment]
完整的stacktrace打印一下？

**Comment by von-eureka** [comment]
>cannot import name 'ServiceContext' from 'llama_index.core' (/home/ureka/.local/lib/python3.10/site-packages/llama_index/core/__init__.py)
  File "/home/ureka/history_rag-master/executor.py", line 12, in <module>
    from llama_index.core import ServiceContext, StorageContext
ImportError: cannot import name 'ServiceContext' from 'llama_index.core' (/home/ureka/.local/lib/python3.10/site-packages/llama_index/core/__init__.py)

**Comment by von-eureka** [comment]
我也不清楚.....但是我按照你的代码修改了以后便可以运行了，谢谢大佬！

**Comment by taiyi7** [comment]
llama_index安装的0.9.39版本不行，换成0.10.6版本也是不行。

Traceback (most recent call last):
  File "/mnt/workspace/rag/history_rag/cli.py", line 1, in <module>
    from executor import MilvusExecutor
  File "/mnt/workspace/rag/history_rag/executor.py", line 12, in <module>
    from llama_index import ServiceContext, StorageContext
ImportError: cannot import name 'ServiceContext' from 'llama_index' (unknown location)


pip list|grep llama
llama-index                         0.10.6
llama-index-agent-openai            0.1.7
llama-index-core                    0.10.68.post1
llama-index-embeddings-openai       0.1.11
llama-index-legacy                  0.9.48.post3
llama-index-llms-openai             0.1.31
llama-index-multi-modal-llms-openai 0.1.9
llama-index-program-openai          0.1.7
llama-index-question-gen-openai     0.1.3
llama-index-readers-file            0.1.33
