### ISSUE TITLE
运行时提示ImportError: ('Cannot import sentence-transformers or torch package,', 'please `pip install torch sentence-transformers`')

### ISSUE THREAD

**Issue by von-eureka** [wxywb/history_rag#52]
已经安装了`sentence-transformers==2.5.0`和`torch==2.2.1`但是仍然提示无法导入
>('Cannot import sentence-transformers or torch package,', 'please `pip install torch sentence-transformers`')
ModuleNotFoundError: No module named 'sentence_transformers'
During handling of the above exception, another exception occurred:
File "/home/ureka/history_rag-master/executor.py", line 145, in __init__
    self.rerank_postprocessor = SentenceTransformerRerank(
  File "/home/ureka/history_rag-master/cli.py", line 30, in run
    self._executor = MilvusExecutor(conf)
  File "/home/ureka/history_rag-master/cli.py", line 120, in <module>
    cli.run()
ImportError: ('Cannot import sentence-transformers or torch package,', 'please `pip install torch sentence-transformers`')

**Comment by wxywb** [comment]
pip list |grep sentence

**Comment by von-eureka** [comment]
`sentence-transformers 2.5.0`

**Comment by wxywb** [comment]
这个是完整的stacktrace吗，为啥我没看出来是哪一行导致的，使用一下git log？

**Comment by von-eureka** [comment]
是的，但我这边没有配置git......
![image](https://github.com/wxywb/history_rag/assets/82219377/07d88a5f-83e3-4d70-9bd2-23aa3de1b2cd)

**Comment by wxywb** [comment]
你在cli.py开头（头两行）加上
```python
import torch 
from sentence_transformers import SentenceTransformer
```
然后执行一下

**Comment by von-eureka** [comment]
直接报错，提示找不到`sentence_transformers` 模块了
![image](https://github.com/wxywb/history_rag/assets/82219377/82be9e78-78f3-486e-9775-ab73ac1b6000)

**Comment by wxywb** [comment]
这意味着你可能存在多个python环境，你pip list的和你从ide里启动的python不是一个，你直接用命令行启动（pip list可以出来的那个环境）

**Comment by von-eureka** [comment]
我退出虚拟环境后跑了一次，没问题了。但是前进到构建索引的时候失败了，报错`MilvusException: <MilvusException: (code=1, message=this version of sdk is incompatible with server, please downgrade your sdk or upgrade your server)>`

![image](https://github.com/wxywb/history_rag/assets/82219377/27c5bc3f-aa95-4011-ba13-6781482f135e)

**Comment by wxywb** [comment]
pip list|grep milvus 
docker ps 分别看看

**Comment by von-eureka** [comment]
pip list|grep milvus
    py milvus    2.3.6
   
    docker ps
    permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/containers/json": dial unix /var/run/docker.sock: connect: permission denied

**Comment by wxywb** [comment]
你的milvus没有启动吗？docker看起来没访问权限？不行走zillizpipeline方案？

**Comment by von-eureka** [comment]
启动了，又检查了一下，把我的用户加入到了docker用户组里，现在`docker ps`是没问题的，但是依旧报错。
![image](https://github.com/wxywb/history_rag/assets/82219377/3b48cf32-d599-40c2-b6a5-d0de7206d629)
报错如下：
![image](https://github.com/wxywb/history_rag/assets/82219377/2a1ddeec-fdbd-4d5c-afb1-b99e92043115)

**Comment by wxywb** [comment]
这个咋是，2.0.2的呢，我repo里安的应该是2.3.0的

**Comment by wxywb** [comment]
你先试试pip install pymilvus==2.0.2

**Comment by von-eureka** [comment]
我试着装了2.3.0版本的pymilvus，还是这个问题；
![image](https://github.com/wxywb/history_rag/assets/82219377/851794ed-1c67-4dc1-a757-ddf33f071ad7)
版本回滚到2.0.2以后，也会报错，只不过错误信息变了
![image](https://github.com/wxywb/history_rag/assets/82219377/8ba4b52a-a240-4e9b-8709-8ea66440171a)

**Comment by von-eureka** [comment]
但是似乎更新的时候没有完全安装
![image](https://github.com/wxywb/history_rag/assets/82219377/1b9f3d80-47ac-4860-99b3-469c91baf9e1)
我试了试升级提到的包，但是告诉我没有适配版本

**Comment by wxywb** [comment]
看起来到2.0.2不可行，你先装上2.3.0安装吧，正常按照文档操作应该就是2.3.0

**Comment by von-eureka** [comment]
好吧，我又重新做了个环境，但是还是不行......我现在换到win环境下试一试，但是也还是报错==
>Traceback (most recent call last):
  File "G:\history_rag-master\cli.py", line 1, in <module>
    from executor import MilvusExecutor
  File "G:\history_rag-master\executor.py", line 12, in <module>
    from llama_index import ServiceContext, StorageContext
  File "C:\Users\Eureka\rag\Lib\site-packages\llama_index\__init__.py", line 13, in <module>
    from llama_index.callbacks.global_handlers import set_global_handler
  File "C:\Users\Eureka\rag\Lib\site-packages\llama_index\callbacks\__init__.py", line 7, in <module>
    from .token_counting import TokenCountingHandler
  File "C:\Users\Eureka\rag\Lib\site-packages\llama_index\callbacks\token_counting.py", line 6, in <module>
    from llama_index.utilities.token_counting import TokenCounter
  File "C:\Users\Eureka\rag\Lib\site-packages\llama_index\utilities\token_counting.py", line 6, in <module>
    from llama_index.llms import ChatMessage, MessageRole
  File "C:\Users\Eureka\rag\Lib\site-packages\llama_index\llms\__init__.py", line 14, in <module>
    from llama_index.llms.anyscale import Anyscale
  File "C:\Users\Eureka\rag\Lib\site-packages\llama_index\llms\anyscale.py", line 10, in <module>
    from llama_index.llms.openai import OpenAI
  File "C:\Users\Eureka\rag\Lib\site-packages\llama_index\llms\openai\__init__.py", line 1, in <module>
    from llama_index.llms.openai.base import AsyncOpenAI, OpenAI, SyncOpenAI, Tokenizer
  File "C:\Users\Eureka\rag\Lib\site-packages\llama_index\llms\openai\base.py", line 16, in <module>
    from llama_index.core.base.llms.types import (
ModuleNotFoundError: No module named 'llama_index.core.base'

我参照了上一个issue的做法，只保留了llama_index，但是还是不行

**Comment by wxywb** [comment]
从我多次解决这个问题的经验来看如果你(当前用的)是llama 0.9.39是可以解决的
1 pip的python和执行的python不是一个
2.存在llama0.10的包
我建议你回到你一个环境 装上db目录下的milvus2.3.3应该就可以解决

**Comment by von-eureka** [comment]
我现在回到了第一个环境，创建了一个新的虚拟环境重新安装了一遍，但是出现了新的报错.....
>Traceback (most recent call last):
  File "/home/ureka/history_rag-master/cli.py", line 123, in <module>
    cli.run()
  File "/home/ureka/history_rag-master/cli.py", line 33, in run
    self._executor = MilvusExecutor(conf)
  File "/home/ureka/history_rag-master/executor.py", line 136, in __init__
    elif config.llm.proxy_model:
AttributeError: 'EasyDict' object has no attribute 'proxy_model'
我看了一下，llama是0.9.39的，milvus是2.3.3的，easydict是1.12的

**Comment by wxywb** [comment]
不好意思，这是最近的一次pr引入的bug，我修了一下，请更新一下最新的代码
https://github.com/wxywb/history_rag/blob/ea66d21129ad22ae37375f11fd86f96172354bc3/executor.py#L136

**Comment by von-eureka** [comment]
解决了，我最后想请教您一个问题：为什么我使用vscode的调试就可以正常运行，而如果使用WSL的bash启动则会报错：
>Traceback (most recent call last):
  File "/home/ureka/history_rag-master/cli.py", line 123, in <module>
    cli.run()
  File "/home/ureka/history_rag-master/cli.py", line 33, in run
    self._executor = MilvusExecutor(conf)
  File "/home/ureka/history_rag-master/executor.py", line 136, in __init__
    elif config.llm.proxy_model:
AttributeError: 'EasyDict' object has no attribute 'proxy_model'

**Comment by wxywb** [comment]
你的wsl bash代码不是最新的，这是最新的136行
https://github.com/wxywb/history_rag/blob/ea66d21129ad22ae37375f11fd86f96172354bc3/executor.py#L136
