### ISSUE TITLE
built文件后报错，不知晓原因，求教

### ISSUE THREAD

**Issue by shawnFuu** [wxywb/history_rag#57]
![{67A0F76D-5CD8-4c27-A8FD-A26CB5234912}](https://github.com/wxywb/history_rag/assets/162449599/806ae6af-c034-4a84-b5ec-0af7b745cf38)
![{E1C72432-64F4-443e-A18D-3378A3A3A18D}](https://github.com/wxywb/history_rag/assets/162449599/7d8849e0-dbdf-4120-9e0b-4cc6db3a9352)
出现报错了，不知晓原因，是否是llms没有设置好？

烦请赐教，感谢！

**Comment by wxywb** [comment]
初步怀疑是网络问题，你可以跟着[这个教程](https://github.com/milvus-io/bootcamp/blob/master/bootcamp/RAG/zilliz_pipeline_rag.ipynb)走一下吗，我想先看看你能否正常使用zilliz. pipeline?

**Comment by shawnFuu** [comment]
我可以在Zilliz的Web UI上正常使用pipeline，但是在python环境能否运行目前还不清楚，应该如何验证？求教

**Comment by wxywb** [comment]
你在web ui上肯定是可以正常使用的
你现在需要跟和教程跑一些这些python代码，我怀疑你的环境可能无法连到服务器，所以你需要跟着执行这些代码。

**Comment by shawnFuu** [comment]
[
![1710263206(1)](https://github.com/wxywb/history_rag/assets/162449599/54c70b54-60be-4e41-a2c7-2dee745959f6)
我运行了教程的代码，主要是运行pipeline对实例数据进行摄取的操作，应该连接服务器没有问题

**Comment by wxywb** [comment]
那你再次运行一下
https://github.com/wxywb/history_rag/blob/ea66d21129ad22ae37375f11fd86f96172354bc3/custom/zilliz/base.py#L130
前面加上print(ingestion_url, self.headers, params) 
然后再次运行 截个图给我，关键信息注意部分遮挡（你的key）

**Comment by shawnFuu** [comment]
![{10D1B536-1C54-471e-B828-EE473A850DE3}](https://github.com/wxywb/history_rag/assets/162449599/323fc499-39ba-4d54-a47b-875f33ff6182)
z
![{47EFF17F-615B-422c-8CB3-6D5B0DFBB2FA}](https://github.com/wxywb/history_rag/assets/162449599/19c1a79b-a7a3-4faa-afda-0268ced41dff)
这次比之前更近了一步，构建了collection并且可以提问，但是提问后就报错了，是否是llm服务器无法连接？还有最后说一个无效的参数，是我的qwen key，但好像并没有成功使用？求教
我给的变量名是 `qwen_key`

**Comment by wxywb** [comment]
你通yqwen的apikey是不是带上换行符了，我看到以\n结尾了

**Comment by wxywb** [comment]
也不一定，你要不发邮件给我你的im（qq，wechat）联系方式吧，我

**Comment by shawnFuu** [comment]
重新申请了API_KEY，并替换好环境变量后就可以正常运行了，遇到类似报错的同学可以跟着[教程](https://help.aliyun.com/zh/dashscope/developer-reference/activate-dashscope-and-create-an-api-key)走一遍，测试一下
