### ISSUE TITLE
Error Code 429

### ISSUE THREAD

**Issue by BrandonBetelgeuse** [wxywb/history_rag#59]
各位好，我尝试在Windows环境下搭设，其他都已经部署完毕，但到提问环节时就会出现如图问题。已经修改gpt4为3.5，且能查询到API Key。因为没有任何计算机基础，所以万望不吝赐教！
![image](https://github.com/wxywb/history_rag/assets/96436506/71eca03c-7beb-425a-b168-a997141a2be8)
![image](https://github.com/wxywb/history_rag/assets/96436506/f43fa1be-7c59-4247-a810-4e2242242d36)
![image](https://github.com/wxywb/history_rag/assets/96436506/65452bb0-5a58-4af7-b183-bd15d01457ed)

**Comment by wxywb** [comment]
你的openai账户欠费了，要充钱。

**Comment by BrandonBetelgeuse** [comment]
感谢您，问题成功解决了！
