### ISSUE TITLE
提问之后的api接口调用错误

### ISSUE THREAD

**Issue by 770asd** [wxywb/history_rag#62]
我用的是GPT-3.5的API_KEY,然后报了如下错误，只能使用GPT-4.0的API接口么，能更换api吗？
![1711372498198](https://github.com/wxywb/history_rag/assets/137772763/0f0250b0-7976-4fa6-b526-04115d1c479f)
![1711372498198](https://github.com/wxywb/history_rag/assets/137772763/a2af4e2a-8253-4275-a3fc-0d45e67f3136)

**Comment by wxywb** [comment]
参考https://github.com/wxywb/history_rag/issues/15
