### ISSUE TITLE
把模型换成gpt-3.5-turbo了，但是回答准确率比较低。

### ISSUE THREAD

**Issue by Prototypeex** [wxywb/history_rag#64]
(rag) 问题: 张飞的妻子是谁？
张飞的妻子是后主敬哀皇后的长女。
+---------------------------------------------------------------------------------------------------------------------+

(rag) 问题: 后主敬哀皇后是谁？
后主敬哀皇后是车骑将军张飞的长女。
+---------------------------------------------------------------------------------------------------------------------+

**Comment by wxywb** [comment]
3.5在这个场景下是不太行。
