### ISSUE TITLE
Exception has occurred: MilvusException <MilvusException: (code=2, message=Fail connecting to server on localhost:19530, illegal connection params or server unavailable)>

### ISSUE THREAD

**Issue by flash201524** [wxywb/history_rag#65]
Exception has occurred: MilvusException
<MilvusException: (code=2, message=Fail connecting to server on localhost:19530, illegal connection params or server unavailable)>
这个怎么解决

**Comment by flash201524** [comment]
我怀疑是环境配置有问题，但是明明是按照流程来的啊

**Comment by flash201524** [comment]
TERMINAL
a11@Steve-Jobs-Macbook-Air ~ % docker ps
CONTAINER ID   IMAGE     COMMAND   CREATED   STATUS    PORTS     NAMES
a11@Steve-Jobs-Macbook-Air ~ %

**Comment by flash201524** [comment]
> 很明显，你的milvus启动失败了

那怎么解决啊😭我是小白不懂这些

**Comment by wxywb** [comment]
正常启动的话你docker ps会有etcd milvus minio等组件

**Comment by flash201524** [comment]
> 正常启动的话你docker ps会有etcd milvus minio等组件，你不会跳过启动milvus这一步了吧

启动milvus是步骤2吗？我现在发现可能之前没有完全搞好？
所以每次电脑重启都要重复步骤2吗？还是不用

**Comment by flash201524** [comment]
正常启动milvus之后好像可以了，不过这个build时间一般要多久啊，又看不到进度的

**Comment by wxywb** [comment]
> 正常启动milvus之后好像可以了，不过这个build时间一般要多久啊，又看不到进度的

看你的机器，我用的NVIDIA GeForce RTX 2080 Ti，三国数据大概要5分钟，24史用了两个小时，如果用cpu会很慢，如果实在没显卡，可以使用pipeline.

**Comment by flash201524** [comment]
> > 正常启动milvus之后好像可以了，不过这个build时间一般要多久啊，又看不到进度的
> 
> 看你的机器，我用的NVIDIA GeForce RTX 2080 Ti，三国数据大概要5分钟，24史用了两个小时，如果用cpu会很慢，如果实在没显卡，可以使用pipeline.

我windows是RTX 3060，但是看了一下资源管理器好像没有用显卡

**Comment by wxywb** [comment]
正常应该用的,看一下你的pytorch是不是有问题, 
```bash
python
```
Python 3.9.7 (default, Sep 16 2021, 13:09:58)
[GCC 7.5.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch.zeros(5).cuda()

tensor([0., 0., 0., 0., 0.], device='cuda:0')

**Comment by flash201524** [comment]
> 正常应该用的,看一下你的pytorch是不是有问题,
> 
> ```shell
> python
> ```
> 
> Python 3.9.7 (default, Sep 16 2021, 13:09:58) [GCC 7.5.0] :: Anaconda, Inc. on linux Type "help", "copyright", "credits" or "license" for more information.
> 
> > > > import torch
> > > > torch.zeros(5).cuda()
> 
> tensor([0., 0., 0., 0., 0.], device='cuda:0')

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "E:\software\Anaconda\Lib\site-packages\torch\cuda\__init__.py", line 293, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled

好奇怪，我明明是装的CUDA版的啊
conda install pytorch torchvision torchaudio pytorch-cuda=12.1 -c pytorch -c nvidia

**Comment by flash201524** [comment]
重装了一下搞定了
