### ISSUE TITLE
90006  zilliz cloud连接异常

### ISSUE THREAD

**Issue by ChineseRommer** [wxywb/history_rag#71]
![Uploading image.png…]()
连接异常，显示collectionName为空。但是我打断点，输出请求报文，参数都正确，collectionName没有为空。

请求报文如下：
post请求的 domain 为:  https://controller.api.gcp-us-west1.zillizcloud.com/v1/pipelines

post请求的 headers 为:  {'Authorization': 'Bearer 04bb57dfdfa05be8fb27fdbac2e14afe779e296b822c6ceca65e2ed3137a39c5cf5ced91e826b86b60af4f632760db1d6b66365c', 'Accept': 'application/json', 'Content-Type': 'application/json'}

post请求的 json 为:  {'name': 'history_rag_ingestion', 'projectId': 'proj-da62c94730702aee29f4b4', 'clusterId': 'in03-e7569fbc6102815', 'newCollectionName': 'history_rag', 'type': 'INGESTION', 'description': 'data ingestion request.', 'functions': [{'name': 'index_my_doc', 'action': 'INDEX_DOC', 'inputField': 'doc_url', 'language': 'CHINESE', 'chunkSize': 500}, {'name': 'keep_digest_from', 'action': 'PRESERVE', 'inputField': 'digest_from', 'outputField': 'digest_from', 'fieldType': 'VarChar'}]}

post请求的 pipeline_ids 为:  {}

报错信息：
(rag) zilliz pipeline 连接异常 {'code': 90006, 'message': 'Invalid pipeline config: collectionName should not be null or empty'}

**Comment by wxywb** [comment]
代码有些过时了，这周我会把这个代码整体更新一下。

**Comment by ChineseRommer** [comment]
可以了，多谢
