### ISSUE TITLE
pipeline模式下使用GPT-4，无法复现演示的问题

### ISSUE THREAD

**Issue by morning0801** [wxywb/history_rag#74]
代码中使用的模型是gpt-4-turbo-2024-04-09，相同的问题我使用GPT-4得到的回答跟您演示的效果不同。这是模型不同造成的吗？
![rag效果](https://github.com/wxywb/history_rag/assets/144869082/229feb8e-3954-436c-a2c4-3696a3934c49)

另外，我收到的回答并不能够准确的给出出处，甚至回复的内容里有原字"《书名》原文内容"。这是为什么？

**Comment by wxywb** [comment]
视频中的内容是用milvus方案实现的，milvus方案利用了文档结构将传记名抽出来作为metainfo，这些逻辑请参考[具体实现](https://github.com/wxywb/history_rag/blob/master/custom/history_sentence_window.py),当时的pipeline还无法做到这种细粒度的控制（整个url文档才有metainfo，不能切段，给每一段加metainfo），现在pipeline有了text模式，用户可以在客户端进行切分，并赋予每段metainfo，但我没更新这一个方式。

**Comment by morning0801** [comment]
没有用milvus方案是因为docker镜像总是拉取失败，报错内容：error pulling image configuration: download failed after attempts=6: dial tcp 69.63.180.173:443: i/o timeout，就先尝试了pipeline。

**Comment by wxywb** [comment]
目前的dockerhub确实普遍出现了这个网络问题，如果要用milvus版，其他的解决方法有：
- 如果你使用MacOS或者linux，可以使用新出的milvus-lite，这是一个很轻量的python library，安装pymilvus>=2.4, uri改写成一个文件名（而不是localhost:19530）。
- 使用zilliz cloud（云版milvus），将uri换成连接zilliz cloud的endpoint。 
- 加入我们的社区，也会有其他途径提供这个。
